openapi: 3.0.0
servers:
  - url: /api/tdp/
info:
  version: 4.0.1
  title: Target Discovery Platform API
components:
  responses:
    error:
      description: Internal Server Error
      content:
        application/json:
          schema:
            title: Error
            type: string
    invalid:
      description: Invalid Request
      content:
        application/json:
          schema:
            title: Error
            type: string
    notFound:
      description: Not Found
      content:
        application/json:
          schema:
            title: Error
            type: string
    notAllowed:
      description: 'Not Allowed to perform the operation, are you logged in?'
      content:
        application/json:
          schema:
            title: Error
            type: string
