openapi: 3.0.0
servers:
  - url: /api/tdp/
info:
  version: 4.0.1
  title: Target Discovery Platform API

tags:
  - name: _security
    description: security relevant queries

security:
  - cookieAuth: []

paths:
  '/../../login':
    post:
      tags:
        - _security
      parameters:
        - name: username
          type: string
          in: query
        - name: password
          type: string
          format: password
          in: query
      security: []    # no authentication
      responses:
        '200':
          description: >
            Successfully authenticated.
          headers:
            Set-Cookie:
              schema:
                type: string

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session  # cookie name
  responses:
    error:
      description: Internal Server Error
      content:
        application/json:
          schema:
            title: Error
            type: string
    invalid:
      description: Invalid Request
      content:
        application/json:
          schema:
            title: Error
            type: string
    notFound:
      description: Not Found
      content:
        application/json:
          schema:
            title: Error
            type: string
    notAllowed:
      description: 'Not Allowed to perform the operation, are you logged in?'
      content:
        application/json:
          schema:
            title: Error
            type: string
