openapi: 3.0.0
paths:
  '/db/{{database}}/{{view}}':
    get:
      description: '{{description}}'
      tags:
        - db
        - db_{{database}}
      parameters:
        - $ref: '#/components/parameters/returnQuery'
        {%- for arg in args %}
        - $ref: '#/components/parameters/arg_{{database}}_{{view}}_{{arg.name}}'
        {%- endfor %}
      responses:
        '200':
          $ref: '#/components/responses/entries_{{database}}_{{view}}'
        '403':
          $ref: '#/components/responses/notAllowed'
        '404':
          $ref: '#/components/responses/notFound'
  '/db/{{database}}/{{view}}/filter':
    get:
      tags:
        - db
        - db_{{database}}
      parameters:
        - $ref: '#/components/parameters/returnQuery'
        {%- for arg in args %}
        - $ref: '#/components/parameters/arg_{{database}}_{{view}}_{{arg.name}}'
        {%- endfor %}
        {%- for filter in filters %}
        - $ref: '#/components/parameters/filter_{{database}}_{{view}}_filter_{{filter}}'
        {%- endfor %}
      responses:
        '200':
          $ref: '#/components/responses/entries_{{database}}_{{view}}'
        '403':
          $ref: '#/components/responses/notAllowed'
        '404':
          $ref: '#/components/responses/notFound'
  '/db/{{database}}/{{view}}/count':
    get:
      tags:
        - db
        - db_{{database}}
      parameters:
        - $ref: '#/components/parameters/returnQuery'
        {%- for arg in args %}
        - $ref: '#/components/parameters/arg_{{database}}_{{view}}_{{arg.name}}'
        {%- endfor %}
        {%- for filter in filters %}
        - $ref: '#/components/parameters/filter_{{database}}_{{view}}_filter_{{filter}}'
        {%- endfor %}
      responses:
        '200':
          $ref: '#/components/responses/queryCount'
        '403':
          $ref: '#/components/responses/notAllowed'
        '404':
          $ref: '#/components/responses/notFound'


components:
  parameters: {% if empty %}{}{% endif %}
    {%- for arg in args %}
    'arg_{{database}}_{{view}}_{{arg.name}}':
      name: {{arg.name}}
      required: true
      in: query
      schema:
        {% if arg.as_list == false %}type: {{arg.type}}{% endif %}
        {% if arg.as_list %}type: array
        items:
          type: {{arg.type}}
        {%- endif %}
        {% if arg.enum %}
        enum:
          {% for e in arg.enum %}- {{e}}
          {% endfor %}
      {%- endif %}
    {%- endfor %}
    {%- for filter in filters %}
    'filter_{{database}}_{{view}}_filter_{{filter}}':
      name: filter_{{filter}}
      required: false
      schema:
        type: string
      in: query
    {%- endfor %}
  responses:
    entries_{{database}}_{{view}}:
      description: Successful response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/entry_{{database}}_{{view}}'
            #oneOf:
            #  - $ref: '#/components/schemas/returnQuery'

  schemas:
    entry_{{database}}_{{view}}:
      type: object
      properties:
        _id:
          type: integer
        id:
          type: string
      additionalProperties: true # TODO
